### ISSUE TITLE
封装算法按照新的 FIP0059 对现有封装流程进行优化

### ISSUE THREAD

**Issue by elvin-du** [ipfs-force-community/venus-core-devs#9]

**Comment by Fatman13** [comment]
Lotus 正在开发 [FIP0059](https://github.com/filecoin-project/lotus/issues/10984)。

背景
- [ ] https://filecoinproject.slack.com/archives/C027TQMUVJN/p1687710296917299

**Comment by Fatman13** [comment]
这个应该没了。还是应该建在 damocles 那边。
